images:
  - "gcr.io/nectar-bazaar/wiz:latest"

steps:

  - id: "Fetch Secrets"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    waitFor: []
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=wiz-codecov-token > covp.txt;
         gcloud secrets versions access latest --secret=pypi-password > pypip.txt'

  - id: "Pull Kind Cluster CI Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "pull"
      - "gcr.io/nectar-bazaar/kind-ci-cluster"

  - id: "Pull Cached Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "pull"
      - "gcr.io/nectar-bazaar/wiz:latest"

  - id: "Build Test Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Pull Cached Image", "Fetch Secrets"]
    args:
      - "build"
      - "."
      - "--cache-from"
      - "gcr.io/nectar-bazaar/wiz:latest"
      - "--build-arg"
      - "CODECOV_TOKEN=$(cat covp.txt)"
      - "-t"
      - "wiz:latest"
      - "-t"
      - "gcr.io/nectar-bazaar/wiz:latest"
      - "-t"
      - "test-image:latest"

  - id: "Run Tests in Virtual Cluster"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Pull Kind Cluster CI Image", "Build Test Image"]
    args:
      - "run"
      - "-v"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "--net=host"
      - "gcr.io/nectar-bazaar/kind-ci-cluster:latest"

  - id: "Publish"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Run Tests in Virtual Cluster"]
    args:
      - 'run'
      - "--env"
      - "PASSWORD=$(cat pypip.txt)"
      - 'wiz:latest'
      - "publish"
