kind: Operation
title: Disable local telemetry storage
info: If using in-cluster storage for telemetry, destroys all related storage resources
synopsis: file::delete-telem-storage-info.html
id: nectar.operations.delete-telem-pvc
preflight_predicates:
  - id: check_current_strategy
    kind: ManifestVariablePredicate
    title: Telemetry is currently stored in-cluster?
    info: "Ensure it makes sense to perform this operation by checking
    the current configurations."
    variable: telem_storage.strategy
    check_against: managed_pvc
    reason: "It seems that telemetry is not
    currently saved to an internal PVC. Proceeding will not do harm but
    it may not be necessary either as it looks like there's nothing to
    change or destroy."
    tone: warning
stages:
  - id: nectar.stages.delete-telem-confirm
    title: Confirm and Delete
    info: Confirm consent and proceed to deleting telemetry-related resources
    steps:
      - id: nectar.steps.delete-telem-confirm
        title: Confirm Consent
        info: "I understand that proceeding will irreversibly
        delete the local telemetry database, erasing all telemetry related
         to updates, variable assignments, and operations."
        reassignments:
          - to: chart
            id: telem_storage.strategy
            value: disabled
        action:
          kind: MultiAction
          title: Delete resources and reload
          info: Delete telem resources and reapply manifest
          sub_actions:
            - kind: DeleteResourcesAction
              resource_selectors:
                - "deployments:telem-redis"
                - "services:telem-redis"
                - "persistentvolumeclaims:telem-redis-pvc"
                - "secrets:telem-redis-secret"
            # - kind: ApplyManifestAction
            #   tam:
            #     type: image
            #     uri: gcr.io/nectar-bazaar/telem-tami
            #     version: 1.0.0
        fields:
          - id: nectar.fields.delete-telem-confirm
            title: I have read and understood the above.
            target: state
            input: CheckboxInput
            default: false
            validation:
              check_against: True
              reason: "Check to continue"