id: nectar.hooks.uninstall.sync-telem
kind: Hook
title: Upload unsynced Telemetry
info: Uploads unsynced operation and update outcomes to Nectar cloud
triggerSelector:
  event: uninstall
action: FlushTelemAction

---

id: nectar.deletion-spec
kind: DeletionSpec
victim_groups:
  - title: Workloads and services we created elsewhere
    matchers:
      - kind: pods
        namespace: "$app"
        label_selectors:
          app: $app
      - kind: services
        namespace: "$app"
        label_selectors:
          app: $app

---

id: post-update
kind: Hook
trigger:
  event: wiz_upgrade
  from_version: 1.02
  to_version: 2.01
action: DoSomething