kind: OperationRunSimulator
namespace: program
id: ops1
preflight: true
validations: true
operation: nectar.operations.telem-storage
stages:
  - stage: nectar.stages.telem-storage
    steps:
      - step: nectar.steps.telem-storage-step-1
        input:
          telem_storage.strategy: managed_pvc

---

kind: OperationRunSimulator
namespace: program
id: ops2
preflight: true
validations: true
operation: nectar.operations.delete-telem-pvc
stages:
  - stage: nectar.stages.delete-telem-confirm
    steps:
      - step: nectar.steps.delete-telem-confirm
        input:
          nectar.fields.delete-telem-confirm: true