kind: Operation
id: nectar.sim.operations.telem
title: Telem Stage Wrapper
stages:
  - nectar.operations.telem.stage-1

---

kind: OperationRunSimulator
namespace: program
id: ops1
preflight: true
validations: true
operation: nectar.sim.operations.telem
stages:
  - stage: nectar.operations.telem.stage-1
    steps:
      - step: nectar.operations.telem.stage-1.step-1
        input:
          telem_storage.strategy: managed_pvc

---

kind: OperationRunSimulator
namespace: program
id: ops2
preflight: true
validations: true
operation: nectar.operations.delete-telem-pvc
stages:
  - stage: nectar.stages.delete-telem-confirm
    steps:
      - step: nectar.steps.delete-telem-confirm
        input:
          nectar.fields.delete-telem-confirm: "true"