kind: Stage
id: nectar.stages.telem-storage
title: Telemetry Storage
info: Configure where telemetry data should be persisted
steps:
  - ice-cream.steps.hpa-vs-static
  - kind: Step
    id: nectar.steps.telem-storage-step-1
    title: Telemetry Persistence
    info: "Nectar saves telemetry for important events so that users
     can later audit their application. For this, a persistent database
     is required. This step helps you decide where and how to host it."
    action:
      kind: ApplyManifestAction
      tam:
        type: image
        uri: gcr.io/nectar-bazaar/telem-tami
        version: 1.0.0
    fields:
      - id: telem_storage.strategy
        title: Database Strategy
        default: managed_pvc
        input:
          kind: SelectInput
          options:
            managed_pvc: "Managed PVC: in-cluster storage managed by Nectar"
            nectar_cloud: "Nectar cloud storage: secure remote database"
            self_managed: "Own storage: you supply a Redis database"
            disabled: "Disabled: telemetry will not be persisted"
        validation:
          - check_against: disabled
            operator: =/=
            tone: warning
            reason: "Auditing will not be available. You can turn this on later."
          - check_against: self_managed
            operator: =/=
            tone: warning
            reason: "You will be responsible for managing this database."
          - check_against: nectar_cloud
            operator: =/=
            tone: error
            reason: "Not available for your current plan"
      - id: telem_storage.host
        title: Redis database host
        validation:
          - kind: FormatPredicate
            check_against: domain
        show_condition:
          challenge: "{telem_storage.strategy}"
          check_against: self_managed
      - id: telem_storage.port
        title: Telem Redis database host
        default: 6379
        validation:
          - kind: FormatPredicate
            check_against: integer
        show_condition:
          challenge: "{telem_storage.strategy}"
          check_against: self_managed

---

kind: Operation
id: nectar.operations.telem-storage
title: Setup Telemetry Storage
synopsis: file::delete-telem-storage-info.html
info: Choose and implement a persistent storage solution for telemetry data.
preflight_predicates:
  - id: check_current_strategy
    kind: ManifestVarComparePredicate
    title: Ensure telemetry storage is currently disabled
    info: "Ensure that telemetry storage is disabled before enabling it."
    variable: telem_storage.strategy
    check_against: disabled
    reason: "It seems that telemetry storage is already enabled. Instead
    of proceeding, disable it safely using the appropriate operation."
    tone: error
stages:
  - nectar.stages.telem-storage
