kind: DeleteResourcesAction
id: nectar.actions.delete-telem-db-resources
resource_selectors:
  - "deployments:telem-db"
  - "services:telem-db"
  - "persistentvolumeclaims:telem-db-pvc"

---

kind: ApplyManifestAction
id: nectar.actions.apply-telem-db-manifest
tam:
  type: server
  uri: https://api.codenectar.com/manifest_servers/nectar/nectarine-telem-database
  version: 1.0.0
values_source_key: prefs
values_root_key: telem_db

---

kind: MultiAction
id: nectar.actions.delete-telem-db-resources-then-apply
sub_actions:
  - nectar.actions.delete-telem-db-resources
  - nectar.actions.apply-telem-db-manifest

---

kind: Iftt
id: nectar.iftts.telem-db-action-iftt
items:
  - predicate:
      challenge: "{operation/telem_db.strategy}"
      check_against: managed_pvc
    value: nectar.actions.delete-telem-db-resources-then-apply
  - predicate: TruePredicate
    value: nectar.actions.delete-telem-db-resources

---

kind: Predicate
id: nectar.predicate.check-telem-is-disabled
title: Ensure telemetry storage is currently disabled
info: "Ensure that telemetry storage is disabled before enabling it."
operator: in
challenge: "{prefs/telem_db.strategy}"
check_against: [disabled, __undefined__]
reason: "It seems that telemetry storage is already enabled. Instead
    of proceeding, disable it safely using the appropriate operation."
tone: error

---

kind: Predicate
id: nectar.predicate.check-telem-is-pvc
title: Ensure Telemetry is currently stored in-cluster
info: "Ensure it makes sense to perform this operation by checking
the current configurations."
challenge: "{prefs/telem_db.strategy}"
check_against: managed_pvc
reason: "It seems that telemetry is not
currently saved to an internal PVC. Proceeding will not do harm but
it may not be necessary either as it looks like there's nothing to
change or destroy."
tone: warning

---

kind: Stage
id: nectar.stages.telem-storage
title: Telemetry Storage
info: Configure where telemetry data should be persisted
steps:
  - kind: Step
    id: nectar.steps.telem-storage-step-1
    title: Telemetry Persistence
    info: "Nectar saves telemetry for important events so that users
     can later audit their application. For this, a persistent database
     is required. This step helps you decide where and how to host it."
    action: nectar.iftts.telem-db-action-iftt
    fields:
      - id: telem_db.strategy
        target: prefs
        title: Database Strategy
        default: disabled
        decorator:
          template: "<p>A MongoDB deployment backed by a PersistentVolumeClaim
          will be create in the {app/ns} namespace.</p><br/> <p>You will be able to
          resize, delete, and backup the database later.</p>"
          show_condition:
            challenge: "{input/telem_db.strategy}"
            check_against: managed_pvc
        input:
          kind: SelectInput
          options:
            - id: managed_pvc
              title: "Managed PVC: in-cluster storage managed by Nectar"
            - id: nectar_cloud
              title: "Nectar cloud storage: secure remote database"
            - id: self_managed
              title: "Own storage: you supply a MongoDB database"
            - id: disabled
              title: "Disabled: telemetry will not be persisted"
        validation:
          - check_against: disabled
            operator: =/=
            tone: warning
            reason: "Auditing will not be available. You can turn this on later."
          - check_against: self_managed
            operator: =/=
            tone: warning
            reason: "You will be responsible for managing this database."
          - check_against: nectar_cloud
            operator: =/=
            tone: error
            reason: "Not available for your current plan"

      - id: telem_db.host
        title: MongoDB database host
        target: prefs
        validation:
          - kind: FormatPredicate
            check_against: domain
        show_condition:
          challenge: "{input/telem_db.strategy}"
          check_against: self_managed

      - id: telem_db.port
        title: MongoDB database host
        target: prefs
        default: 6379
        validation:
          - kind: FormatPredicate
            check_against: integer
        show_condition:
          challenge: "{input/telem_db.strategy}"
          check_against: self_managed

---

kind: Operation
id: nectar.operations.telem-storage
title: Setup Telemetry Storage
synopsis: file::delete-telem-storage-info.html
info: Choose and implement a persistent storage solution for telemetry data.
preflight_predicates:
  - nectar.predicate.check-telem-is-disabled
stages:
  - nectar.stages.telem-storage

---

kind: Operation
title: Disable In-Cluster Telemetry Storage
info: If using in-cluster storage for telemetry, destroys all related storage resources
synopsis: file::delete-telem-storage-info.html
id: nectar.operations.delete-telem-pvc
preflight_predicates:
  - nectar.predicate.check-telem-is-pvc
stages:
  - id: nectar.stages.delete-telem-confirm
    title: Confirm and Delete
    info: Confirm consent and proceed to deleting telemetry-related resources
    steps:
      - id: nectar.steps.delete-telem-confirm
        title: Confirm Consent
        info: "I understand that proceeding will irreversibly
        delete the local telemetry database, erasing all data related
         to updates, variable assignments, and operations."
        reassignments:
          - to: prefs
            id: telem_db.strategy
            value: disabled
        action:
          kind: DeleteResourcesAction
          title: Delete resources and reload
          info: Delete telem resources and reapply manifest
          resource_selectors:
            - "deployments:telem-db"
            - "services:telem-db"
            - "persistentvolumeclaims:telem-db-pvc"
        fields:
          - id: nectar.fields.delete-telem-confirm
            title: I have read and understood the above.
            target: state
            input: CheckboxInput
            validation:
              - check_against: true
                reason: "Check to continue"
