id: nectar.predicate.check-telem-is-disabled
kind: ManifestVariablePredicate
title: Ensure telemetry storage is currently disabled
info: "Ensure that telemetry storage is disabled before enabling it."
variable: telem_db.strategy
check_against: disabled
reason: "It seems that telemetry storage is already enabled. Instead
    of proceeding, disable it safely using the appropriate operation."
tone: error

---

id: nectar.predicate.check-telem-is-pvc
kind: ManifestVariablePredicate
title: Ensure Telemetry is currently stored in-cluster
info: "Ensure it makes sense to perform this operation by checking
the current configurations."
variable: telem_db.strategy
check_against: managed_pvc
reason: "It seems that telemetry is not
currently saved to an internal PVC. Proceeding will not do harm but
it may not be necessary either as it looks like there's nothing to
change or destroy."
tone: warning

---

kind: Stage
id: nectar.stages.telem-storage
title: Telemetry Storage
info: Configure where telemetry data should be persisted
steps:
  - kind: Step
    id: nectar.steps.telem-storage-step-1
    title: Telemetry Persistence
    info: "Nectar saves telemetry for important events so that users
     can later audit their application. For this, a persistent database
     is required. This step helps you decide where and how to host it."
    action:
      kind: ApplyManifestAction
      values_key: prefs
      values_root: telem_db
      tam:
        type: image
        uri: gcr.io/nectar-bazaar/telem-tami
        version: 1.0.0
    fields:
      - id: telem_db.strategy
        title: Database Strategy
        default: managed_pvc
        input:
          kind: SelectInput
          options:
            managed_pvc: "Managed PVC: in-cluster storage managed by Nectar"
            nectar_cloud: "Nectar cloud storage: secure remote database"
            self_managed: "Own storage: you supply a MongoDB database"
            disabled: "Disabled: telemetry will not be persisted"
        validation:
          - check_against: disabled
            operator: =/=
            tone: warning
            reason: "Auditing will not be available. You can turn this on later."
          - check_against: self_managed
            operator: =/=
            tone: warning
            reason: "You will be responsible for managing this database."
          - check_against: nectar_cloud
            operator: =/=
            tone: error
            reason: "Not available for your current plan"
      - id: telem_db.host
        title: MongoDB database host
        validation:
          - kind: FormatPredicate
            check_against: domain
        show_condition:
          challenge: "{telem_db.strategy}"
          check_against: self_managed
      - id: telem_db.port
        title: MongoDB database host
        default: 6379
        validation:
          - kind: FormatPredicate
            check_against: integer
        show_condition:
          challenge: "{telem_db.strategy}"
          check_against: self_managed

---

kind: Operation
id: nectar.operations.telem-storage
title: Setup Telemetry Storage
synopsis: file::delete-telem-storage-info.html
info: Choose and implement a persistent storage solution for telemetry data.
preflight_predicates:
  - nectar.predicate.check-telem-is-disabled
stages:
  - nectar.stages.telem-storage

---

kind: Operation
title: Disable local telemetry storage
info: If using in-cluster storage for telemetry, destroys all related storage resources
synopsis: file::delete-telem-storage-info.html
id: nectar.operations.delete-telem-pvc
preflight_predicates:
  - nectar.predicate.check-telem-is-pvc
stages:
  - id: nectar.stages.delete-telem-confirm
    title: Confirm and Delete
    info: Confirm consent and proceed to deleting telemetry-related resources
    steps:
      - id: nectar.steps.delete-telem-confirm
        title: Confirm Consent
        info: "I understand that proceeding will irreversibly
        delete the local telemetry database, erasing all telemetry related
         to updates, variable assignments, and operations."
        reassignments:
          - to: chart
            id: telem_db.strategy
            value: disabled
        action:
          kind: MultiAction
          title: Delete resources and reload
          info: Delete telem resources and reapply manifest
          sub_actions:
            - kind: DeleteResourcesAction
              resource_selectors:
                - "deployments:telem-db"
                - "services:telem-db"
                - "persistentvolumeclaims:telem-db-pvc"
        fields:
          - id: nectar.fields.delete-telem-confirm
            title: I have read and understood the above.
            target: state
            input: CheckboxInput
            default: false
            validation:
              check_against: True
              reason: "Check to continue"