key: move-to-external-storage
kind: Operation
title: "Move to external storage"
info: "Move the application database from inside the cluster to outside."
categories: ["storage"]
res_access:
  - res: pvc
    verbs: ['delete', 'create']
  - res: deployment
    verbs: ['delete', 'create']
  - res: secret
    verbs: ['create']
stages:
  - key: overview
    title: Overview
    info: You okay with this?
    steps:
      - key: synopsis
        title: Operation Synopsys
        info: "This step does this and that"
        fields:
          - key: field1
            type: select
            options:
              - key: one
                value: One

---

key: "move-to-internal-storage"
kind: Operation
title: "Move to internal storage"
info: "Move the application database from outside the cluster to inside."
categories: ["storage"]
res_access:
  - res: pvc
    verbs: ['delete', 'create']
  - res: deployment
    verbs: ['delete', 'create']
  - res: secret
    verbs: ['create']
stages:
  - key: overview
    title: Overview
    info: You okay with this?
    steps:
      - key: synopsis
        title: Operation Synopsys
        info: "This step does this and that"
        fields:
          - key: field1
            type: select
            options:
              - key: one
                value: One

